from pathlib import Path
import html

import markdown


REPO_ROOT = Path(__file__).resolve().parents[1]
DOCS_DIR = REPO_ROOT / "docs"

SOURCE_FILES = [
    "copilot-tips.md",
    "methodology.md",
    "data-safeguards.md",
]


def first_heading(markdown_text: str, fallback: str) -> str:
    for line in markdown_text.splitlines():
        stripped = line.strip()
        if stripped.startswith("# "):
            return stripped[2:].strip()
    return fallback


def render_page(title: str, body_html: str) -> str:
    escaped_title = html.escape(title)
    return f"""<!doctype html>
<html lang=\"en\">
  <head>
    <meta charset=\"utf-8\" />
    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />
    <title>{escaped_title} | LotusLift</title>
      <meta name=\"description\" content=\"Generated documentation page for the LotusLift modernization enablement program.\" />
    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\" />
    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin />
    <link
      href=\"https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;600;700&family=Sora:wght@500;600;700&family=IBM+Plex+Mono:wght@400;500&display=swap\"
      rel=\"stylesheet\"
    />
    <link rel=\"stylesheet\" href=\"site.css\" />
  </head>
  <body>
    <div class=\"background-grid\" aria-hidden=\"true\"></div>

    <header class=\"topbar\">
      <a class=\"brand\" href=\"index.html\">LotusLift</a>
      <nav>
        <a href=\"index.html\">Home</a>
        <a href=\"method.html\">Method</a>
          <a href=\"workstreams.html\">Workstreams</a>
        <a href=\"security.html\">Security</a>
        <a href=\"copilot-tips.html\">Tips</a>
      </nav>
    </header>

    <main class=\"layout\">
      <section class=\"page-head reveal\">
        <p class=\"eyebrow\">Generated From Markdown</p>
        <h1>{escaped_title}</h1>
        <p>This page is automatically generated from its corresponding Markdown file.</p>
      </section>

      <section class=\"doc-content reveal delay-1\">
{body_html}
      </section>
    </main>

    <footer class=\"layout footer\">
      <p>Generated by scripts/build_docs.py</p>
    </footer>

    <script src=\"site.js\"></script>
  </body>
</html>
"""


def build_markdown_file(source_name: str) -> None:
    source_path = DOCS_DIR / source_name
    output_path = source_path.with_suffix(".html")

    markdown_text = source_path.read_text(encoding="utf-8")
    title = first_heading(markdown_text, source_path.stem.replace("-", " ").title())

    html_body = markdown.markdown(
        markdown_text,
        extensions=["extra", "tables", "fenced_code", "sane_lists"],
    )

    wrapped_html = render_page(title, html_body)
    output_path.write_text(wrapped_html, encoding="utf-8")


def main() -> None:
    for source_name in SOURCE_FILES:
        build_markdown_file(source_name)


if __name__ == "__main__":
    main()
